### ISSUE TITLE
Animated Slider Stops After Box Collapse

### ISSUE THREAD

**Issue by erebuslabs** [rstudio/shinydashboard#69] opened 2015-07-14 19:59 UTC
A box, containing an animated slider:

``` R
box(
   title = "a box",
   collapsible=TRUE,
   collapsed = FALSE,
   sliderInput(inputId = "foo",label="bar",min=0,max=5,value=.25,step=0.05,post = "/1", animate=TRUE)
 )
```

Will work as expected while the box is not collapsed. But if animation begins, and the box is then collapsed, animation ceases.

**Comment by wch** [comment] 2017-01-26 17:52
The issue is that sliders in Shiny don't work when they're hidden, so I'll close the issue here.

**Closed by wch** 2017-01-26 17:52 UTC
