### ISSUE TITLE
shinyapps.io ERROR: could not find function dashboardPage

### ISSUE THREAD

**Issue by EricQLi** [rstudio/shinydashboard#191] opened 2017-02-27 11:14 UTC
When I'm deploying my app on shinyapps.io, it hinted that: ERROR: could not find function dashboardPage And I have tried to remove and reinstall package "shinydashboard" several times, but the error persisted.
How could I solve this problem?

**Comment by bborgesr** [comment] 2017-02-27 14:20
Closing as duplicate of #190

**Closed by bborgesr** 2017-02-27 14:20 UTC
