### ISSUE TITLE
is:open ERROR: there is no package called "shinydashboard"

### ISSUE THREAD

**Issue by EricQLi** [rstudio/shinydashboard#190] opened 2017-02-27 09:41 UTC
When I'm deploying my app on shinyapps.io, it hinted that: ERROR: there is no package called "shinydashboard". And I have tried to remove and reinstall package "shinydashboard" several times, but the error persisted.
How could I solve this problem?

**Comment by bborgesr** [comment] 2017-02-27 14:22
Please do `devtools::session_info()` and copy the output here. Also bear in mind the following (from [this article](https://shiny.rstudio.com/articles/shinyapps.html)):

>### Package sources
> Currently the shinyapps.io service supports deploying packages installed from CRAN, GitHub, and BioConductor. We will look to add support for R-Forge packages in the future.
> 
>#### Important note on GitHub packages
> 
> Only packages installed from GitHub with devtools::install_github in version 1.4 (or later) of devtools are supported. Packages installed with an earlier version of devtools must be reinstalled before you can deploy your application. If you get an error such as “PackageSourceError” when you attempt to deploy, check that you have installed any package from Github with devtools 1.4 or later.

**Comment by EricQLi** [comment] 2017-02-27 16:11
There is no calls to install.packages().

By the way, these packages should be loaded:
require(shinydashboard)
require(Rdonlp2)
require(jpeg)

devtools::session_info()
Session info -------------------------------------------------------------------------------------------------------------------------------------
 setting  value                                              
 version  R version 3.3.2 (2016-10-31)                       
 system   x86_64, mingw32                                    
 ui       RStudio (1.1.88)                                   
 language english                                            
 collate  Chinese (Simplified)_People's Republic of China.936
 tz       Asia/Taipei                                        
 date     2017-02-28                                         

Packages -----------------------------------------------------------------------------------------------------------------------------------------
 package   * version  date       source        
 bitops      1.0-6    2013-08-17 CRAN (R 3.3.0)
 devtools    1.12.0   2016-06-24 CRAN (R 3.3.1)
 digest      0.6.12   2017-01-27 CRAN (R 3.3.2)
 memoise     1.0.0    2016-01-29 CRAN (R 3.3.0)
 packrat     0.4.8-1  2016-09-07 CRAN (R 3.3.2)
 RCurl       1.95-4.8 2016-03-01 CRAN (R 3.3.0)
 RJSONIO     1.3-0    2014-07-28 CRAN (R 3.3.0)
 rsconnect * 0.7      2016-12-21 CRAN (R 3.3.2)
 withr       1.0.2    2016-06-20 CRAN (R 3.3.0)
 yaml        2.1.14   2016-11-12 CRAN (R 3.3.2)

rsconnect::appDependencies()
       package version source
1           R6   2.2.0   CRAN
2         Rcpp  0.12.9   CRAN
3       digest  0.6.12   CRAN
4    htmltools   0.3.5   CRAN
5       httpuv   1.3.3   CRAN
6     jsonlite     1.2   CRAN
7         mime     0.5   CRAN
8      packrat 0.4.8-1   CRAN
9        shiny   1.0.0   CRAN
10 sourcetools   0.1.5   CRAN
11      xtable   1.8-2   CRAN
Warning messages:
1: In value[[3L]](cond) :
  Failed to parse C:/Users/Qi Li/AppData/Local/Temp/RtmpaQKL0t/file237442a64749/app.R ; dependencies in this file will not be discovered.
2: In readLines(appPath) :
  incomplete final line found on 'C:/Users/Qi Li/AppData/Local/Temp/RtmpaQKL0t/file237442a64749/app.R'

**Comment by bborgesr** [comment] 2017-02-27 16:21
I think the problem is with the chinese characters that you seem to have in your app. Try deploying the app manually, using this:

```r
options(encoding = "UTF-8")
deployApp(...)
```

**Comment by bborgesr** [comment] 2017-02-27 16:22
See these two threads for similar problems:

- https://groups.google.com/forum/#!topic/shiny-discuss/bNSl3kj5yQ8
- https://github.com/rstudio/rsconnect/issues/123

**Comment by bborgesr** [comment] 2017-02-27 16:25
cc @kevinushey

**Comment by EricQLi** [comment] 2017-02-27 16:28
Thanks. @bborgesr 
After I deployed the app using options(encoding = "UTF-8")
deployApp(...)
it hints:
Error: Unable to retrieve package records for the following packages:
- "Rdonlp2"

**Comment by bborgesr** [comment] 2017-02-27 16:40
The key thing are these lines:

```
1: In value[3L] :
Failed to parse C:/Users/Qi Li/AppData/Local/Temp/RtmpaQKL0t/file237442a64749/app.R ; dependencies in this file will not be discovered.
2: In readLines(appPath) :
incomplete final line found on 'C:/Users/Qi Li/AppData/Local/Temp/RtmpaQKL0t/file237442a64749/app.R'
```

Do you still get that? You can also try to split your app.R file, so that the Chinese characters are in a different file than the rest of the code (especially the `library(..)` calls). If this still doesn't work, I recommend you open an issue in https://github.com/rstudio/rsconnect/issues since this is a deployment issue, not a shinydashboard issue...

**Comment by EricQLi** [comment] 2017-02-27 16:48
These Warning messages did not occur:
```
1: In value[3L] :
Failed to parse C:/Users/username/AppData/Local/Temp/RtmpaQKL0t/file237442a64749/app.R ; dependencies in this file will not be discovered.
2: In readLines(appPath) :
incomplete final line found on 'C:/Users/username/AppData/Local/Temp/RtmpaQKL0t/file237442a64749/app.R'
```
But the deploying was still not work as:
```
options(encoding = "UTF-8")
deployApp()
Failed to lint file 'app.R'
The linter failed with message:

input string 1 is invalid UTF-8
Failed to lint file 'app.R'
The linter failed with message:

input string 1 is invalid UTF-8
Failed to lint file 'app.R'
The linter failed with message:

input string 1 is invalid UTF-8
Preparing to deploy application...DONE
Uploading bundle for application: 159687...
Error: Unable to retrieve package records for the following packages:
- "Rdonlp2"
```

**Comment by jspiewak** [comment] 2017-02-27 16:59
Please try switching your `require` calls to `library`, as that is how the `rsconnect` package discovers dependencies.

http://docs.rstudio.com/shinyapps.io/getting-started.html#using-your-r-packages-in-the-cloud

**Comment by EricQLi** [comment] 2017-02-27 17:03
> Please try switching your require calls to library, as that is how the rsconnect package discovers dependencies.

The problem persisted.

**Comment by bborgesr** [comment] 2017-02-27 17:31
@EricQLi could you copy paste your app.R if it isn't too long..? We suspect you may have a syntax error...

**Comment by EricQLi** [comment] 2017-02-27 17:42
The code was a bit long, but it worked well on my windows pc.

**Comment by bborgesr** [comment] 2017-02-27 18:18
Closing as the issue was filed in the more appropriate repo: rstudio/rsconnect#161

**Closed by bborgesr** 2017-02-27 18:18 UTC

**Comment by Yuanchao-Xu** [comment] 2017-10-04 07:58
I got the same problem. It seems when there is any non ASCII characters (e.g. Chinese, or only Chinese has this problem?) in the same file with `library()`, shinyapps server just cannot read it, even with encoding changed to utf-8. 

My way of doing it is put the dependencies into a separate file without any non-ASCII characters, and `source` the file in `ur.R` and `server.R`.

**Comment by jspiewak** [comment] 2019-01-22 14:24
@MAbdullah47 I would suggest posting to the [Community](https://community.rstudio.com/c/shiny) with as much of a [reproducible example](https://community.rstudio.com/t/welcome-to-the-rstudio-community/8) as you can share.
