### ISSUE TITLE
Is an option in menuItem() to show menuSubItems on start up feasible?

### ISSUE THREAD

**Issue by pssguy** [rstudio/shinydashboard#64] opened 2015-07-05 03:17 UTC
Currently, you have to click on the arrow of menuItem for the subItems to appear. I might like to indicate the options available to a user when they first visit page

**Comment by pssguy** [comment] 2015-07-05 16:54
Sorry see this has d been addressed #38

**Comment by wch** [comment] 2017-01-26 17:49
Duplicate of #38.

**Closed by wch** 2017-01-26 17:49 UTC
