### ISSUE TITLE
uiOutput in collapsed boxes does not Render

### ISSUE THREAD

**Issue by erebuslabs** [rstudio/shinydashboard#55] opened 2015-06-08 20:46 UTC
Example:
uiOutputs in collapsed boxes do not Render:

**ui.R**
```R
box(
   title = "Column/Variable Names",width = 12,
   collapsible = TRUE,
   collapsed = TRUE, #nothing renders; collapsed=FALSE, # renders as expected
   uiOutput("columnNames")
)
```

**server.R**
The function here is inconsequential - choose any HTML - when columnNames starts collapsed in the UI doesn't render; Not collapsed - it renders.

```R
...
output$columnNames <- renderUI({HTML(string2Input("ds_names_",colnames(dataStore,do.NULL = FALSE))))})
...
```

**Comment by wch** [comment] 2015-06-16 15:52
This sounds like a duplicate of #42, which has been fixed. Can you try this with the development version?

**Closed** 2015-06-16 20:45 UTC
