### ISSUE TITLE
Feature request: Keep the sidebar icons when minimized

### ISSUE THREAD

**Issue by daniel-matthews** [rstudio/shinydashboard#74] opened 2015-07-28 15:10 UTC
Not an issue but a request. I'm sure I cant achieve this with custom CCS but so far no luck. 

Would it be possible to copy the sidebar behavior from https://almsaeedstudio.com/AdminLTE whereby the sidebar remains but as icons? 

Thanks.

**Comment by FrissAnalytics** [comment] 2015-08-04 16:16
if possible I would like to see this as well, perhaps as an optional argument...

**Comment by maxmoro** [comment] 2015-08-04 20:26
+1 for me..

**Comment by wch** [comment] 2017-01-26 17:53
This is a duplicate of #73.

**Closed** 2017-01-26 17:54 UTC
