### ISSUE TITLE
I am using the R Package shinydashboard, now the dashboardSidebar is NOT showing in black background

### ISSUE THREAD

**Issue by gunawebs** [rstudio/shinydashboard#405] opened 2024-02-23 03:50 UTC
Here is my code:

```
dashboardPage(skin="purple",
              dashboardHeader(disable =T),
              dashboardSidebar(
                  dateInput("ProjectStartDate", "Start Date",format = "d-M-yyyy", value = Sys.Date()),
                  sliderInput("NumTasksInParallel", "Parallel Tasks", value=6, min=3, max=10),
                  sliderInput("NumPhasesToRegnerate", "Num Phases", value=4, min=1, max=5),
                  actionButton("GenerateProjectPlanButton", "Run", icon=icon("car"))
              ),
              dashboardBody(
                  fluidRow(
                      box(title="Project Plan GANTT Chart", width=12,solidHeader = TRUE,status="info",
                          plotOutput("GanttChartPlot", height="auto")
                          
                      )
                  )
              )
)
```
It was running fine. But once I upgraded mac OS, shiny package, The left nav is no longer with a darkbackground. And hence unable to see the text. And unable to change the background / font colors

Any help would be greatly appreciated

Working screenshot
<img width="271" alt="image" src="https://github.com/rstudio/shinydashboard/assets/4875731/93591827-ecde-4a68-b8c1-b4e4d8264164">

After the upgrade

<img width="361" alt="image" src="https://github.com/rstudio/shinydashboard/assets/4875731/cb1c0095-767e-4baf-8535-e893f5c3a425">

**Comment by gadenbuie** [comment] 2024-02-23 12:01
Hi @gunawebs, thanks for the report and for including example code. Can you please share the output from `devtools::session_info()`? That will help us know exactly which package version you are using so we can try to debug.

**Comment by gunawebs** [comment] 2024-02-23 13:50
Thanks @gadenbuie 

Here is the session Info

> devtools::session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.2 (2023-10-31)
 os       macOS Sonoma 14.3.1
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Asia/Kolkata
 date     2024-02-23
 rstudio  2023.12.1+402 Ocean Storm (desktop)
 pandoc   NA

─ Packages ─────────────────────────────────────────────────────────────────────────────
 package          * version     date (UTC) lib source
 abind              1.4-5       2016-07-21 [1] CRAN (R 4.3.0)
 base64enc          0.1-3       2015-07-28 [1] CRAN (R 4.3.0)
 bit                4.0.5       2022-11-15 [1] CRAN (R 4.3.0)
 bit64              4.0.5       2020-08-30 [1] CRAN (R 4.3.0)
 bitops             1.0-7       2021-04-24 [1] CRAN (R 4.3.0)
 blob               1.2.4       2023-03-17 [1] CRAN (R 4.3.0)
 bslib              0.6.1       2023-11-28 [1] CRAN (R 4.3.1)
 cachem             1.0.8       2023-05-01 [1] CRAN (R 4.3.0)
 caret            * 6.0-94      2023-03-21 [1] CRAN (R 4.3.0)
 cellranger         1.1.0       2016-07-27 [1] CRAN (R 4.3.0)
 chron              2.3-61      2023-05-02 [1] CRAN (R 4.3.0)
 class              7.3-22      2023-05-03 [1] CRAN (R 4.3.2)
 classInt           0.4-10      2023-09-05 [1] CRAN (R 4.3.0)
 cli                3.6.2       2023-12-11 [1] CRAN (R 4.3.1)
 codetools          0.2-19      2023-02-01 [1] CRAN (R 4.3.2)
 colorspace         2.1-0       2023-01-23 [1] CRAN (R 4.3.0)
 colourpicker     * 1.3.0       2023-08-21 [1] CRAN (R 4.3.0)
 crayon             1.5.2       2022-09-29 [1] CRAN (R 4.3.0)
 crosstalk          1.2.1       2023-11-23 [1] CRAN (R 4.3.1)
 curl               5.2.0       2023-12-08 [1] CRAN (R 4.3.1)
 data.table         1.15.0      2024-01-30 [1] CRAN (R 4.3.1)
 dataMungingUtils * 1.0         2024-02-20 [1] local
 DBI              * 1.2.2       2024-02-16 [1] CRAN (R 4.3.1)
 devtools           2.4.5       2022-10-11 [1] CRAN (R 4.3.0)
 digest           * 0.6.34      2024-01-11 [1] CRAN (R 4.3.1)
 DMwR             * 0.4.1       2013-08-08 [1] Github (cran/DMwR@6fd4f0c)
 dplyr            * 1.1.4       2023-11-17 [1] CRAN (R 4.3.1)
 DT               * 0.32        2024-02-19 [1] CRAN (R 4.3.1)
 e1071              1.7-14      2023-12-06 [1] CRAN (R 4.3.1)
 earth            * 5.3.2       2023-01-26 [1] CRAN (R 4.3.0)
 elasticnet       * 1.3         2020-05-15 [1] CRAN (R 4.3.0)
 ellipsis           0.3.2       2021-04-29 [1] CRAN (R 4.3.0)
 fansi              1.0.6       2023-12-08 [1] CRAN (R 4.3.1)
 farver             2.1.1       2022-07-06 [1] CRAN (R 4.3.0)
 fastmap            1.1.1       2023-02-24 [1] CRAN (R 4.3.0)
 fmsb             * 0.7.6       2024-01-19 [1] CRAN (R 4.3.1)
 fontawesome        0.5.2       2023-08-19 [1] CRAN (R 4.3.0)
 forcats          * 1.0.0       2023-01-29 [1] CRAN (R 4.3.0)
 foreach            1.5.2       2022-02-02 [1] CRAN (R 4.3.0)
 formatR            1.14        2023-01-17 [1] CRAN (R 4.3.0)
 Formula          * 1.2-5       2023-02-24 [1] CRAN (R 4.3.0)
 fs                 1.6.3       2023-07-20 [1] CRAN (R 4.3.0)
 futile.logger    * 1.4.3       2016-07-10 [1] CRAN (R 4.3.0)
 futile.options     1.0.1       2018-04-20 [1] CRAN (R 4.3.0)
 future             1.33.1      2023-12-22 [1] CRAN (R 4.3.1)
 future.apply       1.11.1      2023-12-21 [1] CRAN (R 4.3.1)
 generics           0.1.3       2022-07-05 [1] CRAN (R 4.3.0)
 ggalluvial       * 0.12.5      2023-02-22 [1] CRAN (R 4.3.0)
 ggforce          * 0.4.2       2024-02-19 [1] CRAN (R 4.3.1)
 ggplot2          * 3.4.4       2023-10-12 [1] CRAN (R 4.3.1)
 ggraph           * 2.1.0       2022-10-09 [1] CRAN (R 4.3.0)
 ggrepel          * 0.9.5       2024-01-10 [1] CRAN (R 4.3.1)
 globals            0.16.2      2022-11-21 [1] CRAN (R 4.3.0)
 glue               1.7.0       2024-01-09 [1] CRAN (R 4.3.1)
 gower              1.0.1       2022-12-22 [1] CRAN (R 4.3.0)
 graphlayouts       1.1.0       2024-01-19 [1] CRAN (R 4.3.1)
 gridExtra        * 2.3         2017-09-09 [1] CRAN (R 4.3.0)
 gtable             0.3.4       2023-08-21 [1] CRAN (R 4.3.0)
 hardhat            1.3.1       2024-02-02 [1] CRAN (R 4.3.1)
 hms                1.1.3       2023-03-21 [1] CRAN (R 4.3.0)
 htmltools        * 0.5.7       2023-11-03 [1] CRAN (R 4.3.1)
 htmlwidgets        1.6.4       2024-02-20 [1] Github (ramnathv/htmlwidgets@7928dc2)
 httpuv             1.6.14      2024-01-26 [1] CRAN (R 4.3.1)
 httr               1.4.7       2023-08-15 [1] CRAN (R 4.3.0)
 igraph           * 2.0.2       2024-02-17 [1] CRAN (R 4.3.1)
 ipred              0.9-14      2023-03-09 [1] CRAN (R 4.3.0)
 iterators          1.0.14      2022-02-05 [1] CRAN (R 4.3.0)
 janeaustenr        1.0.0       2022-08-26 [1] CRAN (R 4.3.0)
 jquerylib          0.1.4       2021-04-26 [1] CRAN (R 4.3.0)
 jsonlite           1.8.8       2023-12-04 [1] CRAN (R 4.3.1)
 KernSmooth         2.23-22     2023-07-10 [1] CRAN (R 4.3.2)
 lambda.r           1.2.4       2019-09-18 [1] CRAN (R 4.3.0)
 lars             * 1.3         2022-04-13 [1] CRAN (R 4.3.0)
 later              1.3.2       2023-12-06 [1] CRAN (R 4.3.1)
 lattice          * 0.21-9      2023-10-01 [1] CRAN (R 4.3.2)
 lava               1.7.3       2023-11-04 [1] CRAN (R 4.3.1)
 lazyeval         * 0.2.2       2019-03-15 [1] CRAN (R 4.3.0)
 leaflet          * 2.2.1       2023-11-13 [1] CRAN (R 4.3.1)
 lifecycle          1.0.4       2023-11-07 [1] CRAN (R 4.3.1)
 listenv            0.9.1       2024-01-29 [1] CRAN (R 4.3.1)
 lmtest             0.9-40      2022-03-21 [1] CRAN (R 4.3.0)
 logging          * 0.10-108    2019-07-14 [1] CRAN (R 4.3.0)
 lubridate        * 1.9.3       2023-09-27 [1] CRAN (R 4.3.1)
 magrittr           2.0.3       2022-03-30 [1] CRAN (R 4.3.0)
 maps             * 3.4.2       2023-12-15 [1] CRAN (R 4.3.1)
 MASS               7.3-60      2023-05-04 [1] CRAN (R 4.3.2)
 Matrix             1.6-1.1     2023-09-18 [1] CRAN (R 4.3.2)
 memoise            2.0.1       2021-11-26 [1] CRAN (R 4.3.0)
 mime               0.12        2021-09-28 [1] CRAN (R 4.3.0)
 miniUI             0.1.1.1     2018-05-18 [1] CRAN (R 4.3.0)
 ModelMetrics       1.2.2.2     2020-03-17 [1] CRAN (R 4.3.0)
 munsell            0.5.0       2018-06-12 [1] CRAN (R 4.3.0)
 networkD3        * 0.4         2017-03-18 [1] CRAN (R 4.3.0)
 nlme               3.1-163     2023-08-09 [1] CRAN (R 4.3.2)
 nnet               7.3-19      2023-05-03 [1] CRAN (R 4.3.2)
 parallelly         1.37.0      2024-02-14 [1] CRAN (R 4.3.1)
 pillar             1.9.0       2023-03-22 [1] CRAN (R 4.3.0)
 pipeR            * 0.6.1.3     2016-04-04 [1] CRAN (R 4.3.0)
 pkgbuild           1.4.3       2023-12-10 [1] CRAN (R 4.3.1)
 pkgconfig          2.0.3       2019-09-22 [1] CRAN (R 4.3.0)
 pkgload            1.3.4       2024-01-16 [1] CRAN (R 4.3.1)
 plotly           * 4.10.4      2024-01-13 [1] CRAN (R 4.3.1)
 plotmo           * 3.6.2       2022-05-21 [1] CRAN (R 4.3.0)
 plotrix          * 3.8-4       2023-11-10 [1] CRAN (R 4.3.1)
 pls              * 2.8-3       2023-11-17 [1] CRAN (R 4.3.1)
 plyr             * 1.8.9       2023-10-02 [1] CRAN (R 4.3.1)
 png              * 0.1-8       2022-11-29 [1] CRAN (R 4.3.0)
 polyclip           1.10-6      2023-09-27 [1] CRAN (R 4.3.1)
 pROC               1.18.5      2023-11-01 [1] CRAN (R 4.3.1)
 prodlim            2023.08.28  2023-08-28 [1] CRAN (R 4.3.0)
 profvis            0.3.8       2023-05-02 [1] CRAN (R 4.3.0)
 promises           1.2.1       2023-08-10 [1] CRAN (R 4.3.0)
 proxy              0.4-27      2022-06-09 [1] CRAN (R 4.3.0)
 purrr              1.0.2       2023-08-10 [1] CRAN (R 4.3.0)
 qdapRegex        * 0.7.8       2023-10-17 [1] CRAN (R 4.3.1)
 qdapTools          1.3.7       2023-05-10 [1] CRAN (R 4.3.0)
 quantmod         * 0.4.26      2024-02-14 [1] CRAN (R 4.3.1)
 R.methodsS3      * 1.8.2       2022-06-13 [1] CRAN (R 4.3.0)
 R.oo             * 1.26.0      2024-01-24 [1] CRAN (R 4.3.1)
 R.utils          * 2.12.3      2023-11-18 [1] CRAN (R 4.3.1)
 R2HTML           * 2.3.3       2022-05-23 [1] CRAN (R 4.3.0)
 R6                 2.5.1       2021-08-19 [1] CRAN (R 4.3.0)
 ragg               1.2.7       2023-12-11 [1] CRAN (R 4.3.1)
 randomForest     * 4.7-1.1     2022-05-23 [1] CRAN (R 4.3.0)
 rappdirs           0.3.3       2021-01-31 [1] CRAN (R 4.3.0)
 raster             3.6-26      2023-10-14 [1] CRAN (R 4.3.1)
 RColorBrewer     * 1.1-3       2022-04-03 [1] CRAN (R 4.3.0)
 Rcpp               1.0.12      2024-01-09 [1] CRAN (R 4.3.1)
 RCurl              1.98-1.14   2024-01-09 [1] CRAN (R 4.3.1)
 reactable        * 0.4.4       2023-03-12 [1] CRAN (R 4.3.0)
 reactR             0.5.0       2023-10-11 [1] CRAN (R 4.3.1)
 readr              2.1.5       2024-01-10 [1] CRAN (R 4.3.1)
 readxl           * 1.4.3       2023-07-06 [1] CRAN (R 4.3.0)
 recipes            1.0.10      2024-02-18 [1] CRAN (R 4.3.1)
 remotes            2.4.2.1     2023-07-18 [1] CRAN (R 4.3.0)
 reshape2         * 1.4.4       2020-04-09 [1] CRAN (R 4.3.0)
 rhandsontable    * 0.3.8       2021-05-27 [1] CRAN (R 4.3.0)
 rlang              1.1.3       2024-01-10 [1] CRAN (R 4.3.1)
 RMySQL           * 0.10.27     2023-12-04 [1] CRAN (R 4.3.1)
 ROCR               1.0-11      2020-05-02 [1] CRAN (R 4.3.0)
 rpart              4.1.21      2023-10-09 [1] CRAN (R 4.3.2)
 rpivotTable      * 0.3.0       2024-02-20 [1] Github (smartinsightsfromdata/rpivotTable@bd626a8)
 RSQLite            2.3.5       2024-01-21 [1] CRAN (R 4.3.1)
 rstudioapi         0.15.0      2023-07-07 [1] CRAN (R 4.3.0)
 rvest            * 1.0.4       2024-02-12 [1] CRAN (R 4.3.1)
 sass               0.4.8       2023-12-06 [1] CRAN (R 4.3.1)
 scales           * 1.3.0       2023-11-28 [1] CRAN (R 4.3.1)
 seplyr           * 1.0.4       2021-09-02 [1] CRAN (R 4.3.2)
 sessioninfo        1.2.2       2021-12-06 [1] CRAN (R 4.3.0)
 sf                 1.0-15      2023-12-18 [1] CRAN (R 4.3.1)
 shiny            * 1.8.0       2023-11-17 [1] CRAN (R 4.3.1)
 shinybusy        * 0.3.2       2023-11-23 [1] CRAN (R 4.3.1)
 shinydashboard   * 0.7.2       2021-09-30 [1] CRAN (R 4.3.0)
 shinythemes      * 1.2.0       2021-01-25 [1] CRAN (R 4.3.0)
 shinyWidgets     * 0.8.1       2024-01-10 [1] CRAN (R 4.3.1)
 SnowballC          0.7.1       2023-04-25 [1] CRAN (R 4.3.0)
 sp                 2.1-3       2024-01-30 [1] CRAN (R 4.3.1)
 stringi          * 1.8.3       2023-12-11 [1] CRAN (R 4.3.1)
 stringr          * 1.5.1       2023-11-14 [1] CRAN (R 4.3.1)
 survival           3.5-7       2023-08-14 [1] CRAN (R 4.3.2)
 systemfonts        1.0.5       2023-10-09 [1] CRAN (R 4.3.1)
 TeachingDemos    * 2.13        2024-02-16 [1] CRAN (R 4.3.1)
 terra              1.7-71      2024-01-31 [1] CRAN (R 4.3.1)
 textshaping        0.3.7       2023-10-09 [1] CRAN (R 4.3.1)
 threejs          * 0.3.3       2020-01-21 [1] CRAN (R 4.3.0)
 tibble           * 3.2.1       2023-03-20 [1] CRAN (R 4.3.0)
 tidycensus         1.6         2024-01-25 [1] CRAN (R 4.3.1)
 tidygraph          1.3.1       2024-01-30 [1] CRAN (R 4.3.1)
 tidyr            * 1.3.1       2024-01-24 [1] CRAN (R 4.3.1)
 tidyselect         1.2.0       2022-10-10 [1] CRAN (R 4.3.0)
 tidytext         * 0.4.1       2023-01-07 [1] CRAN (R 4.3.0)
 tigris             2.1         2024-01-24 [1] CRAN (R 4.3.1)
 timechange         0.3.0       2024-01-18 [1] CRAN (R 4.3.1)
 timeDate           4032.109    2023-12-14 [1] CRAN (R 4.3.1)
 tokenizers         0.3.0       2022-12-22 [1] CRAN (R 4.3.0)
 TTR              * 0.24.4      2023-11-28 [1] CRAN (R 4.3.1)
 tweenr             2.0.2       2022-09-06 [1] CRAN (R 4.3.0)
 tzdb               0.4.0       2023-05-12 [1] CRAN (R 4.3.0)
 units              0.8-5       2023-11-28 [1] CRAN (R 4.3.1)
 urlchecker         1.0.1       2021-11-30 [1] CRAN (R 4.3.0)
 usdata           * 0.2.0       2021-06-21 [1] CRAN (R 4.3.0)
 usethis            2.2.3       2024-02-19 [1] CRAN (R 4.3.1)
 utf8               1.2.4       2023-10-22 [1] CRAN (R 4.3.1)
 uuid               1.2-0       2024-01-14 [1] CRAN (R 4.3.1)
 vcd              * 1.4-12      2023-12-29 [1] CRAN (R 4.3.1)
 vctrs              0.6.5       2023-12-01 [1] CRAN (R 4.3.1)
 VennDiagram      * 1.7.3       2022-04-12 [1] CRAN (R 4.3.0)
 viridis            0.6.5       2024-01-29 [1] CRAN (R 4.3.1)
 viridisLite        0.4.2       2023-05-02 [1] CRAN (R 4.3.0)
 visNetwork       * 2.1.2       2022-09-29 [1] CRAN (R 4.3.0)
 vroom              1.6.5       2023-12-05 [1] CRAN (R 4.3.1)
 withr              3.0.0       2024-01-16 [1] CRAN (R 4.3.1)
 wordcloud        * 2.6         2018-08-24 [1] CRAN (R 4.3.0)
 wordcloud2       * 0.2.1       2018-01-03 [1] CRAN (R 4.3.0)
 wrapr            * 2.1.0       2023-08-19 [1] CRAN (R 4.3.0)
 XML                3.99-0.16.1 2024-01-22 [1] CRAN (R 4.3.1)
 xml2               1.3.6       2023-12-04 [1] CRAN (R 4.3.1)
 xtable           * 1.8-4       2019-04-21 [1] CRAN (R 4.3.0)
 xts              * 0.13.2      2024-01-21 [1] CRAN (R 4.3.1)
 yaml               2.3.8       2023-12-11 [1] CRAN (R 4.3.1)
 zipcodeR         * 0.3.5       2022-10-03 [1] CRAN (R 4.3.0)
 zoo              * 1.8-12      2023-04-13 [1] CRAN (R 4.3.0)

 [1] /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library

**Comment by gadenbuie** [comment] 2024-02-23 14:56
Thanks @gunawebs. I can't reproduce the issue you're seeing. Here's what I see, using the same shiny, shinydashboard, and bslib package versions as you.

![image](https://github.com/rstudio/shinydashboard/assets/5420529/60a4c1b7-4a7c-4ff4-88b4-c83f79ab341a)


Most likely the difference is caused by a package or UI element you're including in your bigger app. I'd recommend adding features back into this small example app until you find the component that breaks your sidebar background.

I'm going to close this issue because it's unlikely to be caused by shinydashboard, but please feel free to add a comment if you do find a conflict or problem.

**Closed by gadenbuie** 2024-02-23 14:56 UTC

**Comment by gunawebs** [comment] 2024-02-24 05:56
Thanks @gadenbuie 

I could create a reproducible example. It happens ONLY in the presence of **_navbarPage_**

Kindly test with the below code.
This does NOT happen in earlier versions

Please test using the below code.

Thanks!!


```
library(shiny)
library(shinydashboard)


shinyUI(
    fluidPage(
        titlePanel(title="Dashboard Bug"),br(),
        navbarPage("",inverse = T, id="oneClickTabPanel",
                   tabPanel('Solution Setup',
                            tabPanel('Create Plan & GANTT Chart',
                                     dashboardPage(skin="purple",
                                                   dashboardHeader(disable =T),
                                                   dashboardSidebar(
                                                       selectInput("ProjectModules", "Project Modules",
                                                                   choices = c("ABC", "EFG"), multiple = T),
                                                       hr(),
                                                       dateInput("ProjectStartDate", "Start Date",format = "d-M-yyyy", value = Sys.Date()),
                                                       actionButton("GenerateProjectPlanButton", "Run", icon=icon("car"))
                                                   ),
                                                   dashboardBody(
                                                       fluidRow(
                                                           box(title="Project Plan GANTT Chart", width=12,solidHeader = TRUE,status="info"
                                                           )
                                                       )
                                                       
                                                   )
                                     )
                            )
                   )
        )
    )
   
)
```

**Comment by gunawebs** [comment] 2024-02-25 12:01
@gadenbuie can you please suggest a workaround? 
TThanks

**Comment by gunawebs** [comment] 2024-02-26 16:02
@gadenbuie Pls note that if I replace, navbarPage with tabsetPanel, things work fine. But I would like to avoid that.
Let me know if you can re open this issue, or if you'd like me to open a new one

**Comment by gadenbuie** [comment] 2024-02-26 17:28
Hi @gunawebs, the core issue is that `*Page()` functions are not intended to be nested. While its technically possible and generally works, there should be only one `*Page()` function at the very top of your `ui` definition. When page functions are nested, the kinds of issues you encountered here are expected.

**Comment by gunawebs** [comment] 2024-02-26 22:46
Thanks @gadenbuie 

So I presume you are saying we cannot have dashboardPage under navbarPage.

But JFYI, all this is still working fine in my older mac, with earlier R. So not sure what changed. 

Also I am confused why it just impacts the background of the dashboard page
