### ISSUE TITLE
Is a Back Button possible?

### ISSUE THREAD

**Issue by pssguy** [rstudio/shinydashboard#83] opened 2015-08-06 17:13 UTC
Situation would be when I utilize updateTabItems but then want to return to the earlier tab - with the exact same layout of charts etc.

**Comment by bborgesr** [comment] 2017-04-20 00:08
Sorry for the very late reply. Can you give a reproducible example of what you mean? What exactly do you mean with "the exact same layout of charts etc."?

If all you're trying to achieve is basically back and forward button functionality, you can kind of do that using Shiny's `updateQueryString(queryString, mode = "push")` and the corresponding `getQueryString()` (or `getUrlHash()`) function. The only drawback to this is that it involves updating the URL of the page (either the query string and/or the hash). But it's the only way to do this currently and it doesn't look so terrible to have that info on the URL as well...

Here's an example of what I mean (switch "manually" from one tab to another by clicking on them directly, and then use the back and forward buttons):

```r
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(title = "Simple tabs"),
  dashboardSidebar(
    sidebarMenu(
      id = "tabs",
      menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard")),
      menuItem("Widgets", tabName = "widgets", icon = icon("th"))
    )
  ),
  dashboardBody(
    tabItems(
      tabItem(tabName = "dashboard",
        h2("Dashboard tab content")
      ),
      tabItem(tabName = "widgets",
        h2("Widgets tab content")
      )
    )
  )
)

server <- function(input, output, session) {
  observeEvent(input$tabs, {
    # Drop the leading '#' symbol
    hash <- substring(getUrlHash(), 2)
    
    # This is so we don't 'update' to the tab we're already in (since clicking on 
    # the sidebar already switches tabs.)
    if (hash != input$tabs) {
      # The 'push' argument is necessary so that the hash change event occurs and
      # so that the other observer is triggered.
      updateQueryString(paste0("#", input$tabs), mode = "push")
    }
  })
  
  observeEvent(getUrlHash(), {
    hash <- substring(getUrlHash(), 2)
    updateTabItems(session, "tabs", hash)
  })
}

shinyApp(ui, server)
```

**Comment by bborgesr** [comment] 2017-04-26 05:38
We're trying to wrap up pending issues since we're releasing to CRAN soon, so I'm closing this for now. If this option doesn't cover your use case, please let me know and we can re-open this.

**Closed by bborgesr** 2017-04-26 05:38 UTC
Labels: ready
